apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameclient
spec:
  replicas: 8
  selector:
    matchLabels:
      app: gameclient
  template:
    metadata:
      labels:
        app: gameclient
    spec:
      containers:
      - name: gameclient-app
        image: localhost:5000/gameclient:latest
        env:
          - name: SERVER_HOST
            value: "gameserver.default.svc.cluster.local"
          - name: SERVER_PORT
            value: "80"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
            ephemeral-storage: "10Mi"
          limits:
            memory: "50Mi"
            cpu: "50m"
            ephemeral-storage: "10Mi"

