apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        args:
        - --provider=github
        - --client-id=$(CLIENT_ID)
        - --client-secret=$(CLIENT_SECRET)
        - --email-domain=*  # restrict to specific email domains if needed
        - --cookie-domain=.daske.dk
        - --whitelist-domain=.daske.dk
        - --upstream=http://gameserver.default.svc.cluster.local
        - --http-address=0.0.0.0:4180
        - --redirect-url=https://achtung.daske.dk/oauth2/callback
        - --cookie-secret=$(COOKIE_SECRET)  # generate with `openssl rand -base64 32`
        - --skip-provider-button=true
        - --pass-basic-auth=true
        - --pass-access-token=true
        - --set-authorization-header=true
        - --cookie-secure=true
        - --cookie-refresh=0h
        - --skip-auth-route=^/oauth2/
        - --skip-provider-button=true
        - --skip-auth-preflight=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --set-xauthrequest=true
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: client-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: cookie-secret
        ports:
        - containerPort: 4180

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
  - port: 4180
    targetPort: 4180

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameserver-auth
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "default-oauth2-proxy@kubernetescrd"
spec:
  rules:
  - http:
      paths:
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
      - path: /oauth2/callback
        pathType: Prefix
        backend:
          service:
            name: web-frontend
            port:
              number: 80
