apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
      - name: gameserver-app
        image: k3d-achtung:43365/game-server:latest
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
          - name: GAME
            value: "achtung"
          - name: NUM_PLAYERS
            value: "8"
          - name: TICK_RATE_MS
            value: "50"
          - name: RUST_LOG
            value: "info"

---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  type: ClusterIP
  selector:
    app: gameserver
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameserver-external
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - achtung.daske.dk
      secretName: achtung-daske-dk-tls
  rules:
    - host: achtung.daske.dk
      http:
        paths:
          - path: /join/observer
            pathType: Exact
            backend:
              service:
                name: gameserver
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
