apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: k3d-achtung:43365/website3:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: RUST_LOG
          value: "debug"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth-app
              key: CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth-app
              key: CLIENT_SECRET


---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 8080
