# fly.toml app configuration file generated for achtung on 2023-10-31T16:29:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "achtung"
primary_region = "arn"
kill_signal = "SIGTERM"

[build]

[env]
RUST_LOG = "info"

[http_service]
internal_port = 3030
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
