# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deploy_service/protos/deploy_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'deploy_service/protos/deploy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*deploy_service/protos/deploy_service.proto\x12\x0b\x64\x65ployagent\"G\n\x12\x44\x65ployAgentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\x03\"\xaf\x01\n\x13\x44\x65ployAgentResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.deployagent.DeployAgentResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x03 \x01(\t\x12\x1a\n\x12\x64\x65ployed_image_url\x18\x04 \x01(\t\" \n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"4\n\x12\x44\x65leteAgentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\x03\"\x81\x01\n\x13\x44\x65leteAgentResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.deployagent.DeleteAgentResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xbc\x01\n\x12\x41gentDeployService\x12R\n\x0b\x44\x65ployAgent\x12\x1f.deployagent.DeployAgentRequest\x1a .deployagent.DeployAgentResponse\"\x00\x12R\n\x0b\x44\x65leteAgent\x12\x1f.deployagent.DeleteAgentRequest\x1a .deployagent.DeleteAgentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deploy_service.protos.deploy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPLOYAGENTREQUEST']._serialized_start=59
  _globals['_DEPLOYAGENTREQUEST']._serialized_end=130
  _globals['_DEPLOYAGENTRESPONSE']._serialized_start=133
  _globals['_DEPLOYAGENTRESPONSE']._serialized_end=308
  _globals['_DEPLOYAGENTRESPONSE_STATUS']._serialized_start=276
  _globals['_DEPLOYAGENTRESPONSE_STATUS']._serialized_end=308
  _globals['_DELETEAGENTREQUEST']._serialized_start=310
  _globals['_DELETEAGENTREQUEST']._serialized_end=362
  _globals['_DELETEAGENTRESPONSE']._serialized_start=365
  _globals['_DELETEAGENTRESPONSE']._serialized_end=494
  _globals['_DELETEAGENTRESPONSE_STATUS']._serialized_start=276
  _globals['_DELETEAGENTRESPONSE_STATUS']._serialized_end=308
  _globals['_AGENTDEPLOYSERVICE']._serialized_start=497
  _globals['_AGENTDEPLOYSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
