# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from deploy_service.protos import deploy_service_pb2 as deploy__service_dot_protos_dot_deploy__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in deploy_service/protos/deploy_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentDeployServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeployAgent = channel.unary_unary(
                '/deployagent.AgentDeployService/DeployAgent',
                request_serializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentRequest.SerializeToString,
                response_deserializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentResponse.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/deployagent.AgentDeployService/DeleteAgent',
                request_serializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)


class AgentDeployServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeployAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentDeployServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeployAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployAgent,
                    request_deserializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentRequest.FromString,
                    response_serializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentResponse.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentRequest.FromString,
                    response_serializer=deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deployagent.AgentDeployService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deployagent.AgentDeployService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentDeployService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeployAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deployagent.AgentDeployService/DeployAgent',
            deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentRequest.SerializeToString,
            deploy__service_dot_protos_dot_deploy__service__pb2.DeployAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deployagent.AgentDeployService/DeleteAgent',
            deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentRequest.SerializeToString,
            deploy__service_dot_protos_dot_deploy__service__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
