apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
      - name: gameserver-app
        image: localhost:5000/gameserver:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: GAME
            value: "achtung"
          - name: NUM_PLAYERS
            value: "8"
          - name: TICK_RATE_MS
            value: "50"
          - name: RUST_LOG
            value: "info"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
            ephemeral-storage: "10Mi"
          limits:
            memory: "10Mi"
            cpu: "100m"
            ephemeral-storage: "10Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  type: NodePort
  selector:
    app: gameserver
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000

---
# External Ingress (exposed to the internet)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameserver-external
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gameserver
            port:
              number: 80

---
# Internal Ingress (cluster-internal only)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gameserver-internal
  annotations:
    # This annotation makes it internal only
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    # Optional: you might want to add IP whitelist for internal access
    # traefik.ingress.kubernetes.io/router.middlewares: "default-internal-whitelist@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: gameserver
            port:
              number: 80
