apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
      - name: gameserver-app
        image: localhost:5000/gameserver:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: GAME
            value: "achtung"
          - name: NUM_PLAYERS
            value: "8"
          - name: TICK_RATE_MS
            value: "50"
          - name: RUST_LOG
            value: "info"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
            ephemeral-storage: "10Mi"
          limits:
            memory: "10Mi"
            cpu: "100m"
            ephemeral-storage: "10Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
spec:
  type: ClusterIP
  selector:
    app: gameserver
  ports:
  - port: 80
    targetPort: 8080
