# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import build_service_pb2 as build__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in build_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuildServiceStub(object):
    """Service definition for the Kubernetes build and deploy service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.unary_unary(
                '/buildservice.BuildService/Build',
                request_serializer=build__service__pb2.BuildRequest.SerializeToString,
                response_deserializer=build__service__pb2.BuildResponse.FromString,
                _registered_method=True)
        self.PollBuild = channel.unary_unary(
                '/buildservice.BuildService/PollBuild',
                request_serializer=build__service__pb2.PollBuildRequest.SerializeToString,
                response_deserializer=build__service__pb2.PollBuildResponse.FromString,
                _registered_method=True)
        self.Deploy = channel.unary_unary(
                '/buildservice.BuildService/Deploy',
                request_serializer=build__service__pb2.DeployRequest.SerializeToString,
                response_deserializer=build__service__pb2.DeployResponse.FromString,
                _registered_method=True)


class BuildServiceServicer(object):
    """Service definition for the Kubernetes build and deploy service
    """

    def Build(self, request, context):
        """Start a build job for a container from a git repository
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollBuild(self, request, context):
        """Poll the status of a running build job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deploy(self, request, context):
        """Deploy a built container to the Kubernetes cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Build': grpc.unary_unary_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=build__service__pb2.BuildRequest.FromString,
                    response_serializer=build__service__pb2.BuildResponse.SerializeToString,
            ),
            'PollBuild': grpc.unary_unary_rpc_method_handler(
                    servicer.PollBuild,
                    request_deserializer=build__service__pb2.PollBuildRequest.FromString,
                    response_serializer=build__service__pb2.PollBuildResponse.SerializeToString,
            ),
            'Deploy': grpc.unary_unary_rpc_method_handler(
                    servicer.Deploy,
                    request_deserializer=build__service__pb2.DeployRequest.FromString,
                    response_serializer=build__service__pb2.DeployResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buildservice.BuildService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buildservice.BuildService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuildService(object):
    """Service definition for the Kubernetes build and deploy service
    """

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buildservice.BuildService/Build',
            build__service__pb2.BuildRequest.SerializeToString,
            build__service__pb2.BuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollBuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buildservice.BuildService/PollBuild',
            build__service__pb2.PollBuildRequest.SerializeToString,
            build__service__pb2.PollBuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deploy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buildservice.BuildService/Deploy',
            build__service__pb2.DeployRequest.SerializeToString,
            build__service__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
